### PR TITLE
Remove underscore from public methods

### PR DESCRIPTION
**Pull request by XhmikosR**
I checked as good as I could and these are the ones I noticed; I was experimenting with mangling properties that start with an underscore.

I discovered I had to also [drop one loop in pan-zoom](https://github.com/jakearchibald/svgomg/commit/99664c8d16893fb334ffeccedda3eb22d5438dcb) and after these changes mangling seems to work fine. Should I push the loop drop here?

### CODE REVIEW

**Comment by jakearchibald** [comment]
LGTM so far

**Comment by XhmikosR** [comment]
@jakearchibald should I pick the for loop patch too? Otherwise you can push to this branch if you want, just note that there's no babel and I'm not sure if public fields support matches what you support here (which I don't know exactly BTW).

**Comment by jakearchibald** [comment]
I'll do the public fields bit & push to this branch

**Comment by XhmikosR** [comment]
Just wondering, from your analytics, how many are on Safari < 14? In general, only 2 latest versions are supported in this repo?

**Comment by jakearchibald** [comment]
> Just wondering, from your analytics, how many are on Safari < 14? In general, only 2 latest versions are supported in this repo?

1.7% of users are on those old versions of Safari. Hmm ok, it's not worth breaking things for that many. I'll take a different approach.

Also, eslint's default parser doesn't support class fields, so it'd mean switching to babel's parser.

**Comment by XhmikosR** [comment]
I think so far on main we support the latest 2 versions from all browsers. I tested Safari 13 and it worked on main (a few days ago).

Maybe we should still have a .browserlistrc file for reference even if it's unused? Or add a mention in README.md?

**Comment by jakearchibald** [comment]
Yeah, it's fair to call it out as a policy in the readme

**Comment by jakearchibald** [comment]
Let me know if you're happy with the removal of bind

**Comment by XhmikosR** [comment]
Yup, the diff LGTM. I assume there's no impact in perf due to moving those in the constructor?

**Comment by XhmikosR** [comment]
Diff-wise this is cleaner https://github.com/jakearchibald/svgomg/commit/2896ea7e603d194f238267d0d35e26d474b54415

Maybe we should go with this and I just add your comment?

**Comment by jakearchibald** [comment]
> Diff-wise this is cleaner [2896ea7](https://github.com/jakearchibald/svgomg/commit/2896ea7e603d194f238267d0d35e26d474b54415)

I think we should optimise for code-readability over diff-readability.

The `.bind` pattern I was using becomes a readability problem, because it turns what looks like a prototype method into an instance methods. I'd rather it was obviously an instance method from its declaration. Public class fields are the best way to do this of course, but adding them in the constructor is a decent compromise until those Safari numbers drop.

**Comment by XhmikosR** [comment]
Your call, I don't have strong feelings about this :)

**Review by jakearchibald — APPROVED** [review]
Let's go with this then

**Pull request merged**
