### PR TITLE
Add `type="button"` in buttons.

### PR DESCRIPTION
**Pull request by XhmikosR**
The default is `type="submit"`

### CODE REVIEW

**Comment by TrySound** [comment]
Does it make sense outside of form element?

**Comment by XhmikosR** [comment]
Yeah, it's good practice to explicitly set it.

**Comment by jakearchibald** [comment]
Is there a benefit to this? It doesn't make it show up different to screen readers, for instance.

**Comment by XhmikosR** [comment]
Now it's explicit what we expect the button to be. I mean, these are not forms. :)

And sure, if one's familiar enough with HTML will probably know this, but IMHO it's better to be explicit with the button type since when the type is missing the default is submit.

**Pull request merged**
