### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by XhmikosR**
@jakearchibald feel free to edit this. I felt the previous text was outdated. Basically the only true part is the "detailed options for each plugin" one.

### CODE REVIEW

**Review by jakearchibald — APPROVED** [review]
Oh wow, didn't realise it was that out of date. Thanks!

**Comment by XhmikosR** [comment]
BTW I feel like there's a duplication in the left menu:

* Contribute links to the repo
* About links to the README.md

Perhaps we should combine these two? Although I do feel that the menu is a little empty after that.

**Comment by jakearchibald** [comment]
> Perhaps we should combine these two? Although I do feel that the menu is a little empty after that.

Good point. I'm happy with it looking emptier. The "about" link is pointless IMO. I'll remove it.

**Comment by XhmikosR** [comment]
Haha https://github.com/jakearchibald/svgomg/commit/23d370781d24fb669eac626ce9dabb02c8833ffe

I'll open a PR!

**Pull request merged**
