### PR TITLE
Update CI config

### PR DESCRIPTION
**Pull request by XhmikosR**
Not sure if it's worth splitting the worfklows...

### CODE REVIEW

**Review by jakearchibald — APPROVED** [review]
LGTM

**Comment by XhmikosR** [comment]
@jakearchibald just please change the branch protection rules after this patch :)

**Comment by jakearchibald** [comment]
> @jakearchibald just please change the branch protection rules after this patch :)

As in, remove 'test' and add 'lint' and 'build'?

**Comment by XhmikosR** [comment]
> > @jakearchibald just please change the branch protection rules after this patch :)
> 
> As in, remove 'test' and add 'lint' and 'build'?

Yup, exactly!

**Pull request merged**
