### PR TITLE
Bulk edit: multi-file upload, compress, and download

### PR DESCRIPTION
**Pull request by sompylasar**
Fixes https://github.com/jakearchibald/svgomg/issues/64

- [x] Open SVG multiple.
- [x] Drop multiple.
- [x] Demo multiple.
- [x] List of files in the menu, select one for details.
- [x] View image of the selected file.
- [x] View code of the selected file.
- [x] Copy the text of the selected file.
- [x] Download the selected file.
- [x] Download all the files in a ZIP archive (thanks to jszip).

------

screen shot 2017-06-26 at 2 23 07 am

screen shot 2017-06-26 at 2 28 17 am

screen shot 2017-06-26 at 2 29 54 am

### CODE REVIEW

**Comment by sompylasar** [comment]
@jakearchibald Hi, what are the blockers for this to be reviewed, merged, and published?

**Comment by jakearchibald** [comment]
Apologies, it's just my time. I'll try to get to this next week.

**Comment by jakearchibald** [comment]
This looks great, and I really appreciate you taking the time putting it together, and nudging me to review it.

**Comment by jakearchibald** [comment]
Sorry, this is slipping. Aiming for this week. Haven't forgotten.

**Comment by jakearchibald** [comment]
I've started merging this into a branch. Also taking the opportunity to modernise the build system, and remove some polyfills that aren't needed anymore.

This PR looks great. The only think I'm unsure of is JSZip, since it adds size to the main bundle. I'll probably move it to a worker so it can be loaded async and run on another thread. Also slightly concerned that it means there's two gzip implementations in the project (along with pako). I might look into creating a tiny library that can create zip bundles without compression. However, I'm not going to do that until I know the size & shape of the problem, or if there even is one.

**Comment by sompylasar** [comment]
> The only think I'm unsure of is JSZip, since it adds size to the main bundle. I'll probably move it to a worker so it can be loaded async and run on another thread. Also slightly concerned that it means there's two gzip implementations in the project (along with pako). I might look into creating a tiny library that can create zip bundles without compression. However, I'm not going to do that until I know the size & shape of the problem, or if there even is one.

Does this mean you are delaying the release of this feature to the public at the main website?

I'm sure this can be improved separately after initial release.

**Comment by jakearchibald** [comment]
> Does this mean you are delaying the release of this feature to the public at the main website?

I'm delaying it until I can build it, and the old deps aren't letting me do that.

> I'm sure this can be improved separately after initial release.

Sure, but I have rare time to spend on this, and performance is an important part of the project for me.

Like I said, moving it into a worker is probably enough, and that's pretty easy to do.

**Comment by jakearchibald** [comment]
`page.js` size:

* Before this PR: 39.42k (11.64k gzipped)
* After this PR: 185k (56k gzipped)

I'm kinda more worried about the impact on main thread parse time. That said, shoving jszip into a worker should be fine. In fact, if I move it into the gzip worker that should work out best, as it dedupes pako.

**Comment by jakearchibald** [comment]
I've merged these into https://github.com/jakearchibald/svgomg/tree/next-version, along with an update of the build system & SVGO.

My next step is to move jszip into the gzip worker and get bulk editing working (it fails currently).

I want to have a little think about the UI too. The two download icons are difficult to tell apart, so I'll have a think about a different icon or something.

Also, I don't think the main menu is the best place for the file list. I'll try moving it to the settings menu and see how that looks.

**Comment by sompylasar** [comment]
@jakearchibald While you are thinking how to make it better, maybe let people use what is already there and benefit from that, leave feedback, etc.?

**Comment by jakearchibald** [comment]
There were a few technical issues that mean it couldn't really launch in its current state. Spinning up a worker per SVG doesn't scale, and the workers were loaded pretty late, hurting performance.

I really appreciate the effort you put in here, but I don't think the feature is worth the additional complexity. Providing the SVGO command to process many files at once may be a better way to gain this type of feature.

That said, if you want to deploy your version somewhere, I'm totally fine with that. If anyone asks for bulk editing in the issues, I'll link them to your version.

**Comment by elbotho** [comment]
@sompylasar do you plan on putting it on a github page?

**Comment by sompylasar** [comment]
@elbotho No plans, sorry. I haven't been using this tool for many years.

**Pull request merged**
