### PR TITLE
Fix size mismatch when pasting an SVG

### LINKED ISSUE #140: Identical input/output incorrectly estimates output as larger
> 192 bytes → 193 bytes **100.52%**

Toggling Show Original in the Markup tab shows no change. Is it adding a trailing newline or something?

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500">
  <path d="M111 223L1 332l110 108v-81h194v-54H111v-82zm388-54L389 61v81H195v54h194v82l110-109z"/>
</svg>
```

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #140

### CODE REVIEW

**Comment by jakearchibald** [comment]
Doesn't this mean the size becomes incorrect? If I save the file it'll be bigger than SVGOMG reports, since it'll have extra whitespace.

I think the real issue is that we trim in the input, so the input has been 'preprocessed'.

**Comment by XhmikosR** [comment]
I believe it's a newline somewhere, but I'm not 100% sure. Because we already trim on paste.

**Comment by XhmikosR** [comment]
@jakearchibald yeah, it's the trim on paste. I pushed another patch which removes trim from there.

**Comment by XhmikosR** [comment]
BTW I really miss a Disable All / Enable All button 😛

**Comment by XhmikosR** [comment]
I thought about this and maybe it makes more sense to go with the first patch. I mean, if the input has whitespace, the SVG size shouldn't include that whitespace. I do see your point though...

**Review by jakearchibald — APPROVED** [review]
I'm happy with this. It's SVGO's job to do the optimisation, and it'll trim as part of that. The benefit of having SVGO do it, is it reports that as part of the _output_, whereas previous to this PR we were applying optimisations as part of the input.

I think `.trim()` was used previously because it was convenient for the "is this SVG?" check, but that check changed.

**Pull request merged**
