### PR TITLE
Add `aria-label` in the load file input

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by jakearchibald** [comment]
I don't think this is necessary. The element has `display: none` so it doesn't appear in the a11y tree.

**Comment by XhmikosR** [comment]
I see it being flagged hence this patch. Feel free to close it if you are sure it's fine :)

**Comment by jakearchibald** [comment]
> I see it being flagged hence this patch

What's flagging it?

**Comment by XhmikosR** [comment]
https://squizlabs.github.io/HTML_CodeSniffer/ not sure about axe

**Comment by jakearchibald** [comment]
I think it's misleading to do accessibility work on something that never appears in the AT.

**Pull request closed without merging**
