### PR TITLE
Add CodeQL Action

### PR DESCRIPTION
**Pull request by XhmikosR**
@jakearchibald how about the cron job? We could either change it or drop it if you prefer.

### CODE REVIEW

**Comment by jakearchibald** [comment]
What's the benefit of the cron rather than just doing it on push?

**Comment by XhmikosR** [comment]
It will run regardless if there's a push 😛

BTW can you enable the repo option to "Delete HEAD branches" and enable the Requirement for the main branch to be up to date?

**Comment by jakearchibald** [comment]
But if there's no push, then there's no change, right? Or is it useful because of changes their end?

**Comment by XhmikosR** [comment]
Yeah, the action might be updated on their side.

**Comment by jakearchibald** [comment]
SGTM!

> BTW can you enable the repo option to "Delete HEAD branches" and enable the Requirement for the main branch to be up to date?

Done

**Comment by XhmikosR** [comment]
Feel free to adapt the cron time :)

This will probably highlight 2-3 issues which I'm already seeing on https://lgtm.com/projects/g/jakearchibald/svgomg?mode=list

**Comment by XhmikosR** [comment]
@jakearchibald it seems the option for the main branch to be up to date is not enabled yet :)

**Comment by jakearchibald** [comment]
@XhmikosR can you see it now? Maybe I forgot to hit save

**Comment by jakearchibald** [comment]
oh ffs I see why it isn't working

**Comment by jakearchibald** [comment]
Fixed 😄

**Comment by XhmikosR** [comment]
Now it's all good :)

**Review by jakearchibald — APPROVED** [review]

**Pull request merged**
