### PR TITLE
pan-zoom.js: remove Firefox workaround

### PR DESCRIPTION
**Pull request by XhmikosR**
Not sure what exactly this was supposed to fix/work around, but it might not be needed anymore?

### CODE REVIEW

**Review by jakearchibald — COMMENTED** [review]
It does seem like Firefox is now using a `deltaMode` of pixels rather than lines, but that doesn't stop 'lines' being a thing. Is it worth keeping the workaround here for other possible cases of this, given that it's standard behaviour?

**Comment by jakearchibald** [comment]
It seems like this is still an issue pretty recently https://github.com/pmndrs/use-gesture/issues/236. I can't recreate it locally, but maybe it depends on the type of mouse, or maybe Firefox changed things more recently, but I can't find anything in their bug tracker about it.

**Comment by XhmikosR** [comment]
We can put this on hold if you think it's better. I couldn't replicate the issue personally using the latest Firefox.

**Comment by jakearchibald** [comment]
I couldn't replicate it either, but unlike https://github.com/jakearchibald/svgomg/pull/355, the thing being removed in this PR addresses a feature, not a bug. That feature still exists. https://github.com/pmndrs/use-gesture/issues/236 suggests it's recently used in the wild.

Yeah, I don't think we should ship this change.

**Comment by XhmikosR** [comment]
Marked the PR as draft.

Perhaps we should then change the comment? I'm fine with dropping this patch, I was just going through the codebase for stuff that might be outdated :)

**Pull request closed without merging**
