### PR TITLE
Specify `line-height` on the root element

### LINKED ISSUE #306: `results` jump on some browsers
Noticed this on Firefox on Android and on older iOS Safari. When the results are loaded there is a "jump".

See the attached video for a demo.

https://user-images.githubusercontent.com/349621/134286662-af85e1e2-e7fd-4be8-b050-3d88b0fe0ee8.mp4

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #306

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW this makes me wonder if we should set a root font-size and line-height. But that's for later

**Comment by jakearchibald** [comment]
> BTW this makes me wonder if we should set a root font-size and line-height. But that's for later

Let's do the `line-height` bit in this PR. `line-height: 1.3` on the root element fixes this issue and looks good.

Good spot btw! Seems like it's the arrow char causing the issue. I guess it uses a different font with a different default line-height for that char.

**Comment by XhmikosR** [comment]
Hmm, this changes a lot more cases, though. Are you OK with those changes?

I say we just go with the original patch which is the least intrusive 😛

**Comment by XhmikosR** [comment]
1.25 seems to also work. Your call, I don't have strong feelings either. I'm used to using 1.5 and 1.25 for small text.

**Comment by jakearchibald** [comment]
Yep, this works for me. Better to have line-height set everywhere. I realise it's a layout change across the site, but it looks fine to me. The difference is really minor.

**Comment by jakearchibald** [comment]
(and it fixes the results issue)

**Pull request merged**
